version: '3'
services:
    php-fpm:
        container_name: crm-php-fpm
        hostname: crm-php-fpm
        build:
            context: .docker/php-fpm
        volumes:
#            - ./.docker/php-fpm/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
            - ../src:/var/www/crm
        environment:
              #XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
              PHP_IDE_CONFIG: "serverName=speed"
        depends_on:
            - postgres
        networks:
            - crm_external-php-net
            - internal-php-net
    nginx:
        image: nginx
        container_name: crm-nginx
        hostname: crm-nginx
        volumes:
            - ../src:/var/www/crm
            - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/logs:/var/log/nginx
        ports:
            - ${NGINX_OUT_PORT-60080}:80
        depends_on:
            - php-fpm
        networks:
            - crm_external-php-net
            - internal-php-net
        environment:
            VIRTUAL_HOST: crm.com.ua
            CERT_NAME: crm.com.ua

    postgres: 
        container_name: crm-postgres
        hostname: crm-postgres
        image: postgres:latest
        restart: "no"
#        volumes:
#            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_OUT_PORT-60031}:5432
        environment:
            TZ: Europe/Kiev
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
#            POSTGRES_DATA: ${POSTGRES_DATA}
        networks:
            - internal-php-net
    pgadmin:
        image: dpage/pgadmin4
        container_name: crm-pgadmin
        restart: "no"
        ports:
            - ${PGADMIN_OUT_PORT-60032}:80
        volumes:
            - ./.docker/postgres/servers.json:/pgadmin4/servers.json
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            VIRTUAL_HOST: pg.com.ua
            CERT_NAME: pg.com.ua
        networks:
            - internal-php-net
            - crm_external-php-net
networks:
  internal-php-net:
  crm_external-php-net:
      external: true
